language: node_js
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/tutor_database_testing

node_js:
  - "v12.10.0"

services:
  - postgresql

before_script:
  - psql -c 'create database  tutor_database_testing;' -U postgres
  - psql -U postgres -d tutor_database_testing -a -f databse/tables.sql

addons:
  apt:
    packages:
      - postgresql-server-dev-9.2
